### ISSUE TITLE
pods can not talk via second ip

### ISSUE THREAD

**Issue by ianhe8x** [cni-genie/CNI-Genie#205]
I have an eks cluster, which i removed aws-cni and installed cni-genie, calico, weave.
i created a echo-server pod with `cni: "calico,weave"`, and a echo-client with `cni: "calico,weave"` as well.

From echo-client, i can talk to echo-server via its calico ip, but can not via weave ip.

it only works if my echo-server only has `cni: "weave"`.

```
apiVersion: v1
kind: Pod
metadata:
  name: echo
  labels:
    app: echo
  annotations:
    cni: "calico,weave"
spec:
  containers:
  - name: echo
    image: alpine:latest
    command:
    - sh
    - -c
    - apk add socat && socat -v tcp-l:1234,fork exec:'/bin/cat'
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
